### ISSUE TITLE
Add user info to version control page

### ISSUE THREAD

**Issue by annahprice** [NHS-NSS-transforming-publications/resources#12]
Do you think we should add instructions to the version control page about setting your username/email? Or would this be best in the GitHub guidance (or both)??

**Comment by davidc92** [comment]
Was literally just thinking about this. I think we should add some links to the version control page on how to set it up (and also on how to set up/use an SSH key!) and then have a paragraph or two on how to do it on the GitHub page too.

**Comment by annahprice** [comment]
Yeah sounds like a plan - we can keep it brief but put it in both. I won't have time to get to it yet, so feel free to do it if you want!
